--DDL File For FLIPZON Project.

--PRODUCTS
CREATE TABLE PUBLIC.PRODUCTS (
    PID BIGINT AUTO_INCREMENT,
	NAME VARCHAR(1000) NOT NULL,
	PDESC VARCHAR(5000),
	PRICE DOUBLE DEFAULT 0.00 NOT NULL,
	IMAGE VARCHAR(1000),
	PTYPE VARCHAR(100),
	DIMENSIONS VARCHAR(100),
	CONSTRAINT CONSTRAINT_F PRIMARY KEY (PID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_F ON PUBLIC.PRODUCTS (PID);


--ORDERS
CREATE TABLE PUBLIC.ORDERS (
	OID NUMBER NOT NULL AUTO_INCREMENT,
	QTY INTEGER NOT NULL,
	STATUS VARCHAR(100) NOT NULL,
	PID INTEGER,
	CONSTRAINT ORDERS_FK FOREIGN KEY (PID) REFERENCES PUBLIC.PRODUCTS(PID)
);

--ADDRESS
CREATE TABLE PUBLIC.ADDRESS (
	AID NUMBER NOT NULL AUTO_INCREMENT,
	DOOR_NO VARCHAR(100) NOT NULL,
	APT VARCHAR(500),
	STREET1 VARCHAR(5000) NOT NULL,
	STREET2 VARCHAR(5000) NOT NULL,
	CITY VARCHAR(100) NOT NULL,
	STATE VARCHAR(100) NOT NULL,
	ZIP VARCHAR(100) NOT NULL
);


--USERS
CREATE TABLE PUBLIC.USERS (
	UID NUMBER NOT NULL AUTO_INCREMENT,
	FIRST_NAME VARCHAR(100) NOT NULL,
	LAST_NAME VARCHAR(100) NOT NULL,
	DOB DATE NOT NULL,
	USERNAME VARCHAR(100) NOT NULL,
	PWD VARCHAR(100) NOT NULL,
	AID INTEGER NOT NULL,
	USR_STATUS VARCHAR(100) NOT NULL,
	CONSTRAINT USERS_PK PRIMARY KEY (UID),
	CONSTRAINT USERS_FK FOREIGN KEY (AID) REFERENCES PUBLIC.ADDRESS(AID) ON DELETE CASCADE ON UPDATE CASCADE
);

